### PR TITLE
Resolve possible null value for default_url_options to empty hash

### PR DESCRIPTION
**Pull request by aploshay**
If this assignment returns nil, things get broken, so this adds a nil guard to resume the normal default value of an empty hash.

### CODE REVIEW

**Comment by aploshay** [comment]
@randalldfloyd when [this change was initially made](https://github.com/IU-Libraries-Joint-Development/essi/commit/80b2af7ca7373fec2d722f7d87f01a464805b872#diff-1d98f0039bbc6df92adee882ed99d993L68), do you know why it got values for the production and test environments, but not development?
[relevant commit](https://github.com/IU-Libraries-Joint-Development/essi/commit/80b2af7ca7373fec2d722f7d87f01a464805b872#diff-1d98f0039bbc6df92adee882ed99d993L68)

**Comment by andjsmit** [comment]
I'm finding that this change may break the iiif manifest creation in development as `default_url_options[:host]` is not set.

**Comment by aploshay** [comment]
> I'm finding that this change may break the iiif manifest creation in development as `default_url_options[:host]` is not set.

@andjsmit Can you expand on this?  What conditions do we need to meet to resolve the original issue without creating the one you cite here?

**Comment by randalldfloyd** [comment]
@andjsmit Was there something more we need to do to consider merging this PR?

**Comment by andjsmit** [comment]
@aploshay  @randalldfloyd  What I was running into is that, as is, setting `default_url_options` to an empty hash caused the UV not to load for me because `default_url_options[:host]` was missing. Apparently, this missing value was needed in the iiif manifest creation. This appears to be a development environment only issue and easily fixed by setting the value in configuration. So if that works for everyone, I'm not opposed to merging as is.

**Pull request merged**
