### PR TITLE
Essi 413 uv download

### PR DESCRIPTION
**Pull request by wang58**
The change will fix both ESSI-413 (UV download current view image) and ESSI-414 (UV download original image) issue.

### CODE REVIEW

**Comment by wang58** [comment]
Ok, See the extra commits for the override. 
44bb1b6... is the override file copied from hyrax
66970cd... is the changes.

**Comment by aploshay** [comment]
In ee17ee5, I pulled in the Hyrax 3.x performance improvements based on solrizing `original_file_id`, but not those pertinent to the alpha channels, and worked around updating `VersioningService`.

**Comment by wang58** [comment]
Updated the branch, the uv download worked as expected. The code looked good to me. +1

**Comment by aploshay** [comment]
@randalldfloyd Can you close or update your change request?  Thanks.

**Pull request merged**
