### PR TITLE
ESSI-802 Run jobs depending on file_set parent later in the stack.

### PR DESCRIPTION
**Pull request by dlpierce**
When using the OrderedMembers flavor of actors in combination with remote file uploads, the fileset parent relationship is not always persisted when it is needed for creating certain asynchronous jobs. This queues those jobs again later in the actor stack after the work membership has been saved.

There may still be times when VisibilityCopyJob and InheritPermissionsJob are created with a nil argument, but a workaround is provided to skip those jobs in this case.

Also includes a fix for thread safety (hyrax PR #3477).

### CODE REVIEW

**Review by aploshay — APPROVED** [review]
+1 by inspection

I do like the pattern of a separate commit for a Hyrax vs its customized version, but it's also easy enough to diff our version of `environment.rb` against Hyrax's

**Comment by dlpierce** [comment]
Good point. I split this into 3 commits.

**Review by randalldfloyd — APPROVED** [review]
This seems like a great solution and the PR is in good order.

**Review by randalldfloyd — APPROVED** [review]
+1 This still seems ready to merge, though I don't have time to desk-check it this morning.

**Pull request merged**
